export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const CREATE_MATCH_SUCCESS = "CREATE_MATCH_SUCCESS";
export const CREATE_MATCH_FAIL = "CREATE_MATCH_FAIL";

export const JOIN_MATCH_SUCCESS = "JOIN_MATCH_SUCCESS";
export const JOIN_MATCH_FAIL = "JOIN_MATCH_FAIL";

export const LIST_MATCH_SUCCESS = "LIST_MATCH_SUCCESS";
export const LIST_MATCH_FAIL = "LIST_MATCH_FAIL";

export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAIL = "VOTE_FAIL";

export const VOTE_VALIDATION = "VOTE_VALIDATION";
export const VOTE_VALIDATION_FAIL = "VOTE_VALIDATION_FAIL";

export const DATA_GAME_SUCCESS = "DATA_GAME_SUCCESS";
export const DATA_GAME_FAIL = "DATA_GAME_FAIL";

export const INIT_GAME_SUCCESS = "INIT_GAME_SUCCESS";
export const INIT_GAME_FAIL = "INIT_GAME_FAIL";


export const NUMBER_PLAYERS_SUCCESS = "NUMBER_PLAYERS_SUCCESS";
export const NUMBER_PLAYERS_FAIL = "NUMBER_PLAYERS_FAIL";

export const STATE_MATCH_SUCCESS = "STATE_MATCH_SUCCESS";
export const STATE_MATCH_FAIL = "STATE_MATCH_FAIL";

export const CANDIDATE_DIRECTOR_SUCCESS = "CANDIDATE_DIRECTOR_SUCCESS";
export const CANDIDATE_DIRECTOR_FAIL = "CANDIDATE_DIRECTOR_FAIL";

export const EXTRACT_CARDS_SUCCESS = "EXTRACT_CARDS_SUCCESS";
export const EXTRACT_CARDS_FAIL = "EXTRACT_CARDS_FAIL";

export const DISCARD_CARDS_SUCCESS = "DISCARD_CARDS_SUCCESS";
export const DISCARD_CARDS_FAIL = "DISCARD_CARDS_FAIL";

export const PROCLAMATION_SUCCESS = "PROCLAMATION_SUCCESS";
export const PROCLAMATION_FAIL = "PROCLAMATION_FAIL";

export const DIRECTOR_SET = "DIRECTOR_SET";
export const DIRECTOR_REMOVE = "DIRECTOR_REMOVE";

export const WAITING = "WAITING";
export const INIT_GAME = "INIT_GAME";
export const DEFINE_DIRECTOR = "DEFINE_DIRECTOR";
export const VOTACION = "VOTACION";
export const SHOW_VOTACION = "SHOW_VOTACION";
export const GUESS = "GUESS";
export const AVADA  = "AVADA";
export const DISCARD_MM = "DISCARD_MM";
export const DISCARD_D = "DISCARD_D";
export const PROCLAMATION = "PROCLAMATION";

export const FINISH_GAME = "FINISH_GAME";